language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO="django>=1.7.0,<1.8.0"
  - DJANGO="django>=1.6.0,<1.7.0"
  - DJANGO="django>=1.5.0,<1.6.0"
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com
install:
  - travis_retry pip install pep8==1.5.7
  - travis_retry pip install python-coveralls
  - travis_retry pip install -e .
  - travis_retry pip install $DJANGO
script:
  - coverage run --source=stream_django setup.py test
after_script:
  # ensure we validate against pep standards
  - "pep8 --exclude=migrations --ignore=E501,E225,W293 stream"
after_success:
   - coveralls
