language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO="django>=2.0.0,<2.1.0"
  - DJANGO="django>=1.11.0,<1.12.0"
  - DJANGO="django>=1.10.2,<1.11.0"
  - DJANGO="django>=1.9.3,<1.10.0"
  - DJANGO="django>=1.8.10,<1.9.0"
  - DJANGO="django==1.7.11"
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.5.12"

matrix:
  exclude:
    - python: 2.7
      env: DJANGO="django>=2.0.0,<2.1.0"
    - python: 3.5
      env: DJANGO="django==1.7.11"
    - python: 3.5
      env: DJANGO="django==1.6.11"
    - python: 3.5
      env: DJANGO="django==1.5.12"
    - python: 3.6
      env: DJANGO="django==1.7.11"
    - python: 3.6
      env: DJANGO="django==1.6.11"
    - python: 3.6
      env: DJANGO="django==1.5.12"

notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com
install:
  - travis_retry pip install pep8==1.7.0
  - travis_retry pip install python-coveralls
  - travis_retry pip install -e .
  - travis_retry pip install $DJANGO --upgrade
script:
  - coverage run --source=stream_django setup.py test
after_script:
  # ensure we validate against pep standards
  - "pep8 --exclude=migrations --ignore=E501,E225,W293 stream"
after_success:
   - coveralls
